### ISSUE TITLE
Bug: Android unable to display QMenu within QInput

### ISSUE THREAD

**Issue by nicholaszuccarelli** [pdanpdan/quasar#11]
Android (both browser and Cordova) is unable to show a QMenu within a QInput field when the QInput  is tapped  on.

Video here showing the bug - in this case, I can tap on a `v-slot:append` dropdown icon:

https://user-images.githubusercontent.com/13761766/143984519-6c0874c0-923b-4c18-aa05-3c5678cc6a67.mp4

Video here is on iOS and shows what is meant to happen (tapping on the input still allows you to type and also display the QMenu results)

https://user-images.githubusercontent.com/13761766/143984409-f3305d66-08d3-46dc-8ebd-3a66de7bbf06.MP4

**Comment by pdanpdan** [comment]
I need the code for reproduction, please

**Comment by nicholaszuccarelli** [comment]
No worries. I'll make a sample project for you tomorrow.

**Comment by pdanpdan** [comment]
I think I only need the QInput and the QMenu, to see how they are related to each other and how is the menu shown

**Comment by nicholaszuccarelli** [comment]
https://github.com/nicholaszuccarelli/android-cordova-bugs-nov2021

Can be seen here inside this dialog. I struggle to make the QMenu open. At one point it displayed in the wrong position (which might be related to being able to scroll the entire window when focussing on the input).

The QMenu seemed to be fine within the actual QPage itself, but was not working in the QDialog.

https://user-images.githubusercontent.com/13761766/144150875-4d94c27e-e2d7-4cfa-875a-4f2b736615a4.mp4

**Comment by pdanpdan** [comment]
https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.16.3-beta.3
