### ISSUE TITLE
Bug: Android Cordova - clicking on input box producing weird scrolling results

### ISSUE THREAD

**Issue by nicholaszuccarelli** [pdanpdan/quasar#12]
Bug is only happening on Android Cordova.
Clicking on an input box can produce weird scrolling results.

In the example here, first in the browser - this is how it is meant to react to clicking on the input.
When I switch to the Cordova app, you can see that clicking on the input box will sometimes make me scroll to the bottom of the page.

https://user-images.githubusercontent.com/13761766/143985043-53493e29-f776-4031-a1e6-20870c9c3836.mp4

**Comment by pdanpdan** [comment]
I need a code sample to reproduce

**Comment by nicholaszuccarelli** [comment]
Will do. Will make a sample with all the problems I found in them.

**Comment by nicholaszuccarelli** [comment]
https://github.com/nicholaszuccarelli/android-cordova-bugs-nov2021

Can be seen in this video. If clicking on the QInput in the middle of the page, it would scroll to wierd positions and sometimes scroll to the end of the page.


https://user-images.githubusercontent.com/13761766/144151305-0de397c8-c2f5-4620-ac21-cab62c48f905.mp4

**Comment by pdanpdan** [comment]
https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.16.3-beta.3
