### ISSUE TITLE
Bug: Cordova iOS - QEditor fullscreen mode overlaps statusbar

### ISSUE THREAD

**Issue by nicholaszuccarelli** [pdanpdan/quasar#14]
Toggling the QEditor to fullscreen mode will overlap the iOS statusbar when running via Cordova (pictured below).
Basically becomes impossible to exit fullscreen.

No problems on Android Cordova

![IMG_1468](https://user-images.githubusercontent.com/13761766/144347089-137ebe40-816c-4aa1-87fd-679958818ed2.PNG)

**Comment by pdanpdan** [comment]
Is it different in original v1 (or v2)?
It should also happen the same for:
- QCarousel (fullscreen)
- QTable (fullscreen)

Unfortunately I cannot test Cordova/Capacitor on iOS, so I'll try something in blind :)

**Comment by pdanpdan** [comment]
Please try quasar-pdan-v1.16.3-beta.4 and tell me if it fixes anything.

**Comment by nicholaszuccarelli** [comment]
Will test this too. I'll check on the app running orignal v1.16 and report back.

**Comment by nicholaszuccarelli** [comment]
Okay so this is a problem on original v1.16 as well.
The change you made in beta 4 did not work.

If I could suggest a solution, apply the following CSS somehow (might need to be included for those other components as well):
```
.q-editor.fullscreen {
  padding-top: env(safe-area-inset-top);
}
```

I have a more complex solution to this implemented within my app, so if this solution is not feasible then I can probably just add a fix manually myself.

**Comment by pdanpdan** [comment]
Please check https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.16.3-beta.5

**Comment by nicholaszuccarelli** [comment]
Fixed! Thank you :)
