### ISSUE TITLE
Bug: QMenu popping up in incorrect position

### ISSUE THREAD

**Issue by nicholaszuccarelli** [pdanpdan/quasar#15]
Since this beta (1.16.3-beta.3)
On PC my QMenus are popping up in the incorrect position now. I have a toolbar at the bottom of the screen and they are now falling below the screen, whereas previously it would previously position itself above its button.

![image](https://user-images.githubusercontent.com/13761766/144374736-859ca8de-4849-4695-80b4-c4aafe4dc4db.png)

**Comment by pdanpdan** [comment]
A small code repro, please.

**Comment by pdanpdan** [comment]
Please check if quasar-pdan-v1.16.3-beta.4 fixes it.

Please recheck also https://github.com/pdanpdan/quasar/issues/10 (the part about the position of the menus in dialog) to see if we didn't break it.

**Comment by nicholaszuccarelli** [comment]
No worries. Will check now. If there are any issues I'll add the broken changes to the git project.

**Comment by nicholaszuccarelli** [comment]
Okay so the original problem has been fixed in beta 4, however the way the QMenu interacts is still not perfect on desktop.

In this video, comparing original v1.16 to beta 4, you can see that as I scroll the page on v1.16, the QMenu will recalculate its position, however on beta 4 it will stay in the same position (under or over) the button.

https://github.com/nicholaszuccarelli/android-cordova-bugs-nov2021

https://user-images.githubusercontent.com/13761766/144413969-0921fa36-c2c8-429f-9451-a93f6b57a4ee.mp4

**Comment by pdanpdan** [comment]
https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.16.3-beta.5

This is by design, in my version menu/tooltip works like this:
- if the anchor element is fixed positioned in page than uses as canvas size the screen
- else it uses the document (including the scroll outside of screen)

So now if you have space to scroll the menu into view than the menu is still rendered in the same position

**Comment by nicholaszuccarelli** [comment]
I see, fair enough :)
Personally it feels a little weird because in dialogs/anchor elements they act the same whereas the document is different. But it is fine otherwise. (Feel free to close if you want).

Anyway, I tested it on PC, iOS and Android and they are all working fine now! Happy days.
