### ISSUE TITLE
Bug: QTabPanels not scrollable 

### ISSUE THREAD

**Issue by nicholaszuccarelli** [pdanpdan/quasar#16]
Noticed when I was looking at your documentation

https://pdanpdan.github.io/quasar-docs/vue-components/carousel

Click on these different tabs and you'll notice that the QTabPanel main area no longer becomes scrollable.

![image](https://user-images.githubusercontent.com/13761766/144951482-912baf68-c8dd-4a14-99bd-25d9f3a5d298.png)

**Comment by pdanpdan** [comment]
Found it, thank you.

https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.16.3-beta.9
