### ISSUE TITLE
Bug - Beta v24 - Containerised QLayout not displaying QDrawer

### ISSUE THREAD

**Issue by nicholaszuccarelli** [pdanpdan/quasar#4]
(This has happened after I switched to this branch of Quasar)

I've found a bug where a QDrawer in a containerised QLayout fails to display fixed to the side on desktop mode (it instead displays in overlay mode).
The width of the page is greater than the defined breakpoint, however it is not displaying the QDrawer correctly.

https://codepen.io/zuc0001/pen/XWerOwb

**Comment by pdanpdan** [comment]
https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.16.0-beta.26
