### ISSUE TITLE
Bug - Beta v24 - QRouteTab no longer binding router specific attributes to HTML tag

### ISSUE THREAD

**Issue by nicholaszuccarelli** [pdanpdan/quasar#5]
Using QRouteTab is no longer binding router-specific classes and attributes to the actual HTML element.

For example, on the regular version of Quasar, my QRouteTabs will each have classes "q-router-link", "q-router-link--active" (etc), and a href="" attribute for SEO purposes, however after switching to this branch, all these properties no longer exist on the QRouteTab attributes.

Clicking the actual tab still correctly redirects to the defined `to` prop, but as mentioned, the actual HTML source doesn't display the `href='` attribute making it invalid for SEO.

(This problem doesn't exist for QTab acting as a route - they still correctly bind the attributes)

**Comment by pdanpdan** [comment]
Can you check if you really had `q-router-link` class on the tabs (and it is not added by you) - I'm not talking about `q-router-link--active`?

**Comment by nicholaszuccarelli** [comment]
Yep, I compared the running code on our production server and I certainly didn't add the classes manually. Code was identical, except one was running on beta v24.

**Comment by pdanpdan** [comment]
`q-router-link`?

**Comment by nicholaszuccarelli** [comment]
Both don't have `q-router-link`.

Below is when the router tab is active.

On v24 beta: (Notice how href is also missing)

![image](https://user-images.githubusercontent.com/13761766/143848500-9667572f-a939-484b-aa95-4456e3f4c15b.png)

On production (v1.16 official)

![image](https://user-images.githubusercontent.com/13761766/143848477-163e2b03-2ea1-453c-9427-93df850f6283.png)

**Comment by pdanpdan** [comment]
That was what I was asking, because there was no `q-router-link` before and I needed to confirm your:
```
my QRouteTabs will each have classes "q-router-link", "q-router-link--active" (etc)
```

**Comment by nicholaszuccarelli** [comment]
Oh my bad then, sorry about that. I should clarify that the `q-router-link--active` classes etc aren't being bound anymore, but instead using `q-tab--active`. Plus href not being bound either.
The `q-router-link--active` one I suppose can be bound using the `exact-active-class` prop (unless it is actually a bug).

**Comment by pdanpdan** [comment]
All the rest is done :) but that class `q-router-link` puzzled me because it was nowhere in original Q1

**Comment by nicholaszuccarelli** [comment]
Haha sorry again. And thanks a lot for fixing the three bugs. I will continue testing the version tomorrow and report back if I find anything else. Rest seems solid so far.

**Comment by pdanpdan** [comment]
https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.16.0-beta.26
