### ISSUE TITLE
Bug - Beta v24 - QChip not binding `q-dark` CSS class when `dark` prop is used

### ISSUE THREAD

**Issue by nicholaszuccarelli** [pdanpdan/quasar#6]
Pretty self explanatory.

Regular Quasar version 1 binds a `q-dark` CSS class when the `dark` prop is used on a QChip.
This automatically makes the text color white instead of having to manually define `text-color="white"`.

This CSS class is not being bound on this version of Quasar.

https://codepen.io/zuc0001/pen/JjrPzOy

**Comment by pdanpdan** [comment]
Can you find where `dark` changed the color of the text in either Q1 or Q2? :)
It only make the icon color to be inherited from the chip, but you always have to set the text color.

**Comment by nicholaszuccarelli** [comment]
This is from regular v1
adding the `dark` prop would add the CSS class `q-dark` which appended the specified CSS to the entire chip (including the text).

![image](https://user-images.githubusercontent.com/13761766/143824679-f74903d5-4a88-4a1d-bb4e-d289c8f54ecc.png)

**Comment by pdanpdan** [comment]
https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.16.0-beta.26
