### ISSUE TITLE
Unable to switch from official 1.16 > Beta 1.16-beta.26

### ISSUE THREAD

**Issue by nicholaszuccarelli** [pdanpdan/quasar#7]
This is going to sound very weird.
Had no issues yesterday on my Windows PC (changed the Quasar version to this version), ran `npm install` and it worked perfectly.

Today I am trying to test on my Mac with Cordova iOS apps, however `npm install` keeps failing.

I've tried uninstalling npm completely, deleting .lock, deleting node_modules, changing around the `eslint` package versions, and absolutely nothing works.

If I change `quasar` back to `^1.16.0` and run `npm install`, it works and builds with no issues.
Struggling to understand why this could suddenly be happening.

![image](https://user-images.githubusercontent.com/13761766/143951089-606d50b4-3693-4024-b9d9-6df397e8a472.png)

The package.lock ESlint version dependencies 
I have tried changing these to match EXACTLY what is defined in your `ui/package.json` and it still fails to build.

![image](https://user-images.githubusercontent.com/13761766/143951165-aacdc295-ab1c-4aa5-8228-9dd94f1e15f3.png)

**Comment by pdanpdan** [comment]
It should not be necessary to change anything except quasar in package.json
But from my experience npm on windows sometimes creates problems.
Maybe you should try to clean npm cache - `npm cache clean --force`
If you use yarn it's `yarn cache clean`
But i would always suggest using yarn on windows

**Comment by nicholaszuccarelli** [comment]
No luck. This is on Mac btw (Windows works perfectly).

Tried cache clean ^, deleting all files, reinstalling NPM/Node (using npm 8.1.4 - same as Windows), and it keeps failing at the `npm install` stage. Even tried install --force and still no luck.
Struggling to work out why this is happening only on Mac when I try using this git repo.

**Comment by pdanpdan** [comment]
I re-read the issue and it looks like you are on mac.
 - change the package.json to the original state (the one in your original project, without changes)
 - add (or replace) the quasar key in dependencies with `"quasar": "https://github.com/pdanpdan/quasar#quasar-pdan-v1.16.0-beta.26"`
 - `rm -rf node_modules yarn.lock package-lock.json`
 - `yarn`
 - `quasar dev -m ...`

**Comment by pdanpdan** [comment]
It looks to me that npm is trying to build quasar
https://github.com/npm/npm/issues/3055
Please don't use npm, they have such interesting ideas :)

**Comment by nicholaszuccarelli** [comment]
Very odd. I followed the yarn steps and had no issues.
I'm trying to understand why npm had no issues on Windows but keeps failing now on Mac.
I might try and find a way to disable prepublish? Unfortunately we have a complex dev environment and for the time being it is easiest for us to stick with npm.

**Comment by pdanpdan** [comment]
I'll try to publish a version without the prepublish script tomorrow

**Comment by nicholaszuccarelli** [comment]
I got it to work finally. 
`npm install --ignore-scripts`
That skipped the prepublish stage. Seems to be working now. Very weird.

BUT
I thought I'd try it with a clean install on Windows (rm node-modules and package-lock.json) and the error is happening on Windows too now.
Again, running install with `--ignore-scripts` fixes it.

**Comment by nicholaszuccarelli** [comment]
Yeah you might need to publish a version without prepublish. Seems that npm likes to build git project URLs from scratch.

**Comment by pdanpdan** [comment]
https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.16.0-beta.27
