### ISSUE TITLE
Bug: Reopening a QDialog crashes with $el of undefined error

### ISSUE THREAD

**Issue by nicholaszuccarelli** [pdanpdan/quasar#8]
As per this example, attempting to relaunch a dialog (making it close, then reopening (typically using $nextTick or setTimeout) will throw a reading $el of undefined error.
Did not have this error on normal Quasar v1.16.0

Example:
https://codepen.io/zuc0001/pen/rNGNGMQ?editors=1011

More details on the error when I replicated the bug in my app:

![image](https://user-images.githubusercontent.com/13761766/143968648-4ea94ba5-4d1c-4ca9-85a6-cca0357f28aa.png)

(QDialog.js)
![image](https://user-images.githubusercontent.com/13761766/143968696-e1931c40-7560-48d0-a6eb-40e936ec81d6.png)

(portal.js)
![image](https://user-images.githubusercontent.com/13761766/143968727-6bb1a3e8-aab2-4a90-92e5-61358d042690.png)

**Comment by pdanpdan** [comment]
https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.16.0-beta.27
