### ISSUE TITLE
Bug: QColor - muted colors on color strip

### ISSUE THREAD

**Issue by nicholaszuccarelli** [pdanpdan/quasar#9]
Can be seen in the docs. Also happening on my dev environment.

https://pdanpdan.github.io/quasar-docs/vue-components/color-picker#basic

![image](https://user-images.githubusercontent.com/13761766/143969114-372707db-39c4-480c-8bbc-46d78647d6f4.png)

The colors on the color strip are muted whereas they should be more vibrant (v2 Quasar)
![image](https://user-images.githubusercontent.com/13761766/143969146-b3e8cac1-19bb-4225-ac45-a7d28368490b.png)

**Comment by pdanpdan** [comment]
https://github.com/pdanpdan/quasar/releases/tag/quasar-pdan-v1.16.0-beta.27
